# Generated by Django 4.2.2 on 2023-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=True, max_length=1000)),
                ('design', models.CharField(max_length=1000)),
                ('poster', models.CharField(max_length=1000)),
                ('pluto', models.BooleanField(default=True)),
                ('orbitline', models.BooleanField(default=True)),
                ('daychart', models.BooleanField(default=False)),
                ('zodiacwheel', models.BooleanField(default=True)),
                ('moon', models.BooleanField(default=True)),
                ('datetime', models.CharField(default=True, max_length=1000)),
                ('locationselect', models.CharField(default=True, max_length=1000)),
                ('titletext', models.CharField(blank=True, max_length=1000, null=True)),
                ('defaultfnote', models.CharField(blank=True, max_length=1000, null=True)),
                ('specialmoment', models.CharField(default=True, max_length=1000)),
                ('posteronly', models.CharField(blank=True, max_length=1000, null=True)),
                ('woodenframe', models.CharField(blank=True, max_length=1000, null=True)),
                ('matelframe', models.CharField(blank=True, max_length=1000, null=True)),
                ('hanger', models.CharField(blank=True, max_length=1000, null=True)),
                ('screenshort', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
