# Generated by Django 4.2.2 on 2023-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetdata',
            name='size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
