# Generated by Django 4.2.2 on 2023-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_planetdata_solarsystem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetdata',
            name='moon_panel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
