# Generated by Django 4.2.2 on 2023-08-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_planetdata_moon_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetdata',
            name='selected_poster',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
