# Generated by Django 4.2.2 on 2023-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0005_planetdata_selected_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetdata',
            name='selected_poster',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
