# Generated by Django 4.1.7 on 2023-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_remove_planetdata_moon_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetdata',
            name='download_url',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
